kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: npd
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: npd
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: npd
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: npd
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: npd
  namespace: kube-system
